---

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Docker Service
  service:
    name: docker
    state: started
    enabled: true

- import_tasks: offline.yml  
  tags: 
    - docker_images

...
